### ISSUE TITLE
work good on 1.6.1.4 but broken on 1.7.0.5

### ISSUE THREAD

**Issue by fghi** [jalik/jalik-ufs#141]
hi, i use ufs and ufs-local
works perfect on meteor 1.6.1.4
but not on meteor 1.7.0.5 : 
- the upload is stalled
- the onProgress seems not triggered
but there is no error message

**Comment by fghi** [comment]
with another try (on 1.7.0.3) i got an error message 

W20180925-12:26:25.725(2)? (STDERR) (node:7297) UnhandledPromiseRejectionWarning: Error: Match error: Expected string, got undefined
W20180925-12:26:25.726(2)? (STDERR)     at check (packages/check/match.js:36:17)
W20180925-12:26:25.726(2)? (STDERR)     at LocalStore.Store.self.checkToken (packages/jalik:ufs/ufs-store.js:139:17)
W20180925-12:26:25.726(2)? (STDERR)     at WebApp.connectHandlers.use (packages/jalik:ufs/ufs-server.js:149:24)
...

**Comment by fghi** [comment]
for more investigations please continue here : 

https://forums.meteor.com/t/solved-how-to-downgrade-jalik-ufs-jalik-ufs-local-issue/45685/9
