### ISSUE TITLE
Meteor.userId can only be invoked in method calls.

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#21]
Why can I not use Meteor.userId in collection.js ?

**Error Message**

W20151019-12:35:48.616(-4)? (STDERR) Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20151019-12:35:48.618(-4)? (STDERR)     at AccountsServer.userId (accounts_server.js:80:13)
W20151019-12:35:48.618(-4)? (STDERR)     at Object.Meteor.userId (accounts_common.js:222:19)
```W20151019-12:35:48.618(-4)? (STDERR)     at [object Object].UploadFS.store.Local.onRead (packages/me_mypack/collections.js:22:1)```
W20151019-12:35:48.618(-4)? (STDERR)     at Object.path [as handle] (packages/jalik_ufs/ufs-server.js:156:1)
W20151019-12:35:48.618(-4)? (STDERR)     at next (/Users/me/.meteor/packages/webapp/.1.2.2.v8ezdl++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151019-12:35:48.619(-4)? (STDERR)     at Function.app.handle (/Users/me/.meteor/packages/webapp/.1.2.2.v8ezdl++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
W20151019-12:35:48.619(-4)? (STDERR)     at Object.fn [as handle] (/Users/me/.meteor/packages/webapp/.1.2.2.v8ezdl++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:74:14)
W20151019-12:35:48.619(-4)? (STDERR)     at next (/Users/me/.meteor/packages/webapp/.1.2.2.v8ezdl++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151019-12:35:48.619(-4)? (STDERR)     at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/packages/webapp.js:370:1)
W20151019-12:35:48.619(-4)? (STDERR)     at packages/webapp/packages/webapp.js:633:1

**My package.js includes this line:**

`api.add_files("collections.js");`

**collections.js (available on client & server)**

```javascript
/////////////////////////////////////
// Define server & client collections.
/////////////////////////////////////

//mypack_std_out = new Mongo.Collection("mypack_std_out");
//mypack_std_err = new Mongo.Collection("mypack_std_err");
mypack_log = new Mongo.Collection("mypack_log");
mypack_jobs = new Mongo.Collection("mypack_jobs");
mypack_uploads = new Mongo.Collection("mypack_uploads");

// Uploaded files are stored here.
mypack_uploads_store = new UploadFS.store.Local({
	collection: mypack_uploads,
	name: 'mypack_uploads',
	path: '~/mypack_uploads',

	// Called before reading file to check if we can return it.
	onRead: function (fileId, request, response) {
		var doc = mypack_uploads.findOne(fileId);
		if (doc) {
			// User must own file to download it.
			if (doc.userId !== Meteor.userId()) {
				throw new Meteor.Error(403, 'this file is private');
			}
		} else {
			throw new Meteor.Error(404, 'file not found');
		}
	},

	// Called when file has been uploaded.
	onFinishUpload: function (file) {
		console.log(file.name + ' has been uploaded');
	}
});
```

**Comment by firewater** [comment]
Sorry, it seems the correct way to get the logged in user ID is with `request.userId`.
