### ISSUE TITLE
Production: MongoError about multi server upsert must include _id

### ISSUE THREAD

**Issue by jonycfu** [jalik/jalik-ufs#77]
Started running into this issue on production recently with Meteor 1.4.1, 
Using the GridFS Stores along with `matb33/collection-hooks`.
Hosting my file uploads on compose.io (Amazon).  

Everything works as usual on local. But for production, I find the following error for some of my file uploads (still investigating the source of error). FYI I'm still quite new to Mongo, and am trying to understand the multiple config servers upsert issue.

```
 method 'ufsCreate' { 
  stack: 'MongoError: upserts to multiple config servers must include _id\n
  
  at Object.Future.wait (/mnt/app/bundle/programs/server/node_modules/fibers/future.js:449:15)\n
  
  at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)\n
  
  at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:771:49)\n
  at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:107:1)\n    
  at [object Object].update (packages/mongo/collection.js:589:29)\n    
  at [object Object].upsert (packages/mongo/collection.js:676:15)\n    
  at packages/matb33_collection-hooks/upsert.js:101:1\n    
  at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    
  at Object.directOp (packages/matb33_collection-hooks/collection-hooks.js:21:1)\n    
  at [object Object].<anonymous> (packages/matb33_collection-hooks/upsert.js:100:1)\n        
  at Function.MongoError.create (/mnt/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)\n    
  at /mnt/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:456:72\n    
  at authenticateStragglers (/mnt/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:404:16)\n    
  at [object Object].messageHandler (/mnt/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:438:5)\n    
  at TLSSocket.<anonymous> (/mnt/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:304:22)\n    
  at emitOne (events.js:77:13)\n    
  at TLSSocket.emit (events.js:169:7)\n    
  at readableAddChunk (_stream_readable.js:153:18)\n    
  at TLSSocket.Readable.push (_stream_readable.js:111:10)\n
  at TLSWrap.onread (net.js:536:20)',
  source: 'method' 
}

```
What is the suggested approach to addressing this issue? 
Anyone come across this issue before?

**Comment by jalik** [comment]
Hi @jonycfu, I think I can resolve this.
I havn't the env (multiple servers) to test if the fix works but it seems easy to fix.
I just need to use an Insert or and update instead of an upsert so the error will not be triggered.

**Comment by jonycfu** [comment]
@jalik Thank you so much! Let me know which branch/commit and I'll test it out on my end if need be :-)

**Comment by jonycfu** [comment]
@jalik Just tried it on production with the multi-server env. Checks out 👍

**Comment by cyx-charan** [comment]
Hey,
I got the same error when I am trying to use compose's mongo instance with a parse server. Can you explain me what exactly is the issue about??

Thanks,
Charan.

**Comment by jalik** [comment]
@cyx-charan, are you sure you got the same issue ? @jonycfu said it was resolved and since I don't use `upsert` it should not happen anymore.. please make sure you have the latest version of UFS.

**Comment by cyx-charan** [comment]
@jalik I am not using jalik-ufs but I got a similar error message and I couldn't find info about anywhere else but here. So just wanted to know more about the issue. My problem is resolved now. Thanks!!

**Comment by jalik** [comment]
@cyx-charan StackOverflow is a great place to find solutions to your problems. Please be kind in the future to not "pollute" project's issues. As many developers I am supporting my projects on free time for free. I am sure you understand that it's not the place where you should post your own issues.. Still I am glad you fixed your problem. ;)

**Comment by cyx-charan** [comment]
@jalik I am really sorry about it :)
